
# ValueError - object is of the right type, but contains an inappropriate value

int("daa") # ValueError 